FROM eclipse-temurin:21-jre-alpine-3.23

WORKDIR /app

COPY apps/content-migration/build/libs/jilinjobs-cms-content-migration-0.1.0-SNAPSHOT.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
