#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

mode="${1:-full}"
state_root="$repo_root/.local-ci"
cache_root="$state_root/cache"
evidence_root="$state_root/evidence"
run_id="$(date -u +%Y%m%dT%H%M%SZ)-$$"
run_root="$state_root/work/$run_id"
evidence_dir="$evidence_root/$run_id"
lock_dir="$state_root/lock"

gradle_image="${LOCAL_CI_GRADLE_IMAGE:-gradle:9.6.1-jdk21}"
node_image="${LOCAL_CI_NODE_IMAGE:-node:24-bookworm-slim}"
mysql_image="${LOCAL_CI_MYSQL_IMAGE:-mysql:8.4}"
playwright_image="${LOCAL_CI_PLAYWRIGHT_IMAGE:-mcr.m.daocloud.io/playwright:v1.61.0-noble}"
alpine_image="${LOCAL_CI_ALPINE_IMAGE:-alpine:3.23}"
builder="${LOCAL_CI_BUILDER:-jilinjobs-cms-ci}"
base_ref="${LOCAL_CI_BASE_REF:-origin/main}"
npm_registry="${LOCAL_CI_NPM_REGISTRY:-https://registry.npmmirror.com/}"
buildkit_config="$state_root/buildkitd.toml"
builder_config_fingerprint_file="$state_root/builder-config.sha256"

mysql_container="jilinjobs-local-ci-mysql"
backend_container="jilinjobs-local-ci-backend"
frontend_container="jilinjobs-local-ci-frontend"
uid="$(id -u)"
gid="$(id -g)"

usage() {
  cat <<'EOF'
Usage:
  scripts/local-ci.sh              # full local Docker CI (default)
  scripts/local-ci.sh full         # same as default
  scripts/local-ci.sh status       # Docker/project cache status
  scripts/local-ci.sh clean        # remove only jilinjobs-cms local CI images/cache/runtime

Environment:
  LOCAL_CI_BASE_REF=origin/main
  LOCAL_CI_FORCE_SPECIALIZED=true
  LOCAL_CI_BUILDER=jilinjobs-cms-ci
  LOCAL_CI_*_IMAGE=<override pinned runtime image>
  LOCAL_CI_PLAYWRIGHT_IMAGE=mcr.microsoft.com/playwright:v1.61.0-noble
  LOCAL_CI_NPM_REGISTRY=https://registry.npmmirror.com/

The full path is completion evidence. It uses fresh writable database/runtime state,
but reuses dependency/build caches and verified local component images by actual
worktree input fingerprints.
EOF
}

say() { printf '\n==> %s\n' "$*"; }
die() { printf 'local-ci: %s\n' "$*" >&2; exit 1; }
remove_container() { docker rm -f "$1" >/dev/null 2>&1 || true; }

write_buildkit_config() {
  local mirrors_json
  mirrors_json="$(docker info --format '{{json .RegistryConfig.Mirrors}}')"
  python3 - "$buildkit_config" "$mirrors_json" <<'PY'
import json
import pathlib
import sys
from urllib.parse import urlparse

path = pathlib.Path(sys.argv[1])
mirrors = []
for raw in json.loads(sys.argv[2] or "[]"):
    parsed = urlparse(raw)
    value = (parsed.netloc + parsed.path).rstrip("/") if parsed.scheme else raw.rstrip("/")
    if value and value not in mirrors:
        mirrors.append(value)

lines = [
    "# Generated by scripts/local-ci.sh from the host Docker daemon registry mirrors.",
    "# Local execution state only; do not commit this file.",
]
if mirrors:
    lines += [
        '[registry."docker.io"]',
        "  mirrors = [" + ", ".join(json.dumps(item) for item in mirrors) + "]",
    ]
else:
    lines += ["# No host Docker Hub registry mirrors are configured; BuildKit will use Docker Hub directly."]

path.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY
}

ensure_builder() {
  write_buildkit_config
  local desired current
  desired="$(sha256sum "$buildkit_config" | awk '{print $1}')"
  current="$(cat "$builder_config_fingerprint_file" 2>/dev/null || true)"

  if ! docker buildx inspect "$builder" >/dev/null 2>&1 || [[ "$current" != "$desired" ]]; then
    docker buildx rm -f "$builder" >/dev/null 2>&1 || true
    docker buildx create --name "$builder" --driver docker-container \
      --buildkitd-config "$buildkit_config" --bootstrap >/dev/null
    printf '%s\n' "$desired" > "$builder_config_fingerprint_file"
    return
  fi

  docker buildx inspect "$builder" --bootstrap >/dev/null
}

acquire_lock() {
  if mkdir "$lock_dir" 2>/dev/null; then
    printf '%s\n' "$$" > "$lock_dir/pid"
    return
  fi

  local lock_pid=""
  lock_pid="$(cat "$lock_dir/pid" 2>/dev/null || true)"
  if [[ "$lock_pid" =~ ^[0-9]+$ ]] && kill -0 "$lock_pid" 2>/dev/null; then
    die "another local CI run appears active (pid $lock_pid): $lock_dir"
  fi

  rm -rf "$lock_dir" || die "cannot remove stale local CI lock: $lock_dir"
  mkdir "$lock_dir" || die "cannot acquire local CI lock after stale-lock cleanup: $lock_dir"
  printf '%s\n' "$$" > "$lock_dir/pid"
  printf 'Recovered stale local CI lock.\n'
}

cleanup_runtime() {
  remove_container "$backend_container"
  remove_container "$frontend_container"
  remove_container "$mysql_container"
  remove_container cms-backend
  remove_container cms-frontend
  remove_container review-baseline-backend
  remove_container review-baseline-copy
  if [[ -d "$run_root" ]]; then
    rm -rf "$run_root" 2>/dev/null || docker run --rm \
      -v "$state_root:/state" "$alpine_image" \
      rm -rf "/state/work/$run_id" >/dev/null
  fi
  rm -rf "$lock_dir" >/dev/null 2>&1 || true
}

project_image_refs() {
  docker image ls --format '{{.Repository}}:{{.Tag}}' \
    | grep '^jilinjobs-cms-local/' \
    | grep -v '<none>' || true
}

clean_project_cache() {
  say "Remove local CI runtime containers"
  cleanup_runtime
  local refs
  refs="$(project_image_refs)"
  if [[ -n "$refs" ]]; then
    printf '%s\n' "$refs" | xargs -r docker image rm -f
  fi
  if docker buildx inspect "$builder" >/dev/null 2>&1; then
    docker buildx prune --builder "$builder" --all --force
  fi
  rm -rf "$state_root"
}

status_project_cache() {
  docker version --format 'Docker server {{.Server.Version}}'
  docker system df
  printf '\nProject local CI images:\n'
  project_image_refs
  if docker buildx inspect "$builder" >/dev/null 2>&1; then
    printf '\nBuilder cache (%s):\n' "$builder"
    docker buildx du --builder "$builder" 2>/dev/null || printf 'Builder cache is currently inactive; the next build will bootstrap it.\n'
  fi
  if [[ -f "$evidence_root/latest.txt" ]]; then
    printf '\nLatest evidence: %s\n' "$(cat "$evidence_root/latest.txt")"
  fi
}

case "$mode" in
  -h|--help|help) usage; exit 0 ;;
  status) status_project_cache; exit 0 ;;
  clean) clean_project_cache; exit 0 ;;
  full) ;;
  *) usage >&2; exit 2 ;;
esac

command -v docker >/dev/null || die "docker is required"
command -v git >/dev/null || die "git is required"
command -v python3 >/dev/null || die "python3 is required for repository-owned verification helpers"
command -v curl >/dev/null || die "curl is required for runtime probes"
command -v sha256sum >/dev/null || die "sha256sum is required"
docker info >/dev/null || die "Docker daemon is not available"
docker buildx version >/dev/null || die "docker buildx is required"

mkdir -p "$state_root" "$cache_root/gradle" "$cache_root/npm" "$evidence_root" "$run_root" "$evidence_dir"
find "$evidence_root" -mindepth 1 -maxdepth 1 -type d -printf '%T@ %p\n' \
  | sort -nr | awk 'NR>3 {sub(/^[^ ]+ /, ""); print}' \
  | xargs -r rm -rf
acquire_lock

for review_container in jilinjobs-human-review-mysql cms-backend cms-frontend; do
  if [[ "$(docker inspect --format '{{.State.Running}}' "$review_container" 2>/dev/null || true)" == "true" ]]; then
    rm -rf "$lock_dir" >/dev/null 2>&1 || true
    die "Human Review Runtime container $review_container is running; execute bash scripts/human-review.sh stop before full Local Docker CI"
  fi
done
trap cleanup_runtime EXIT INT TERM

say "Ensure project-dedicated BuildKit builder: $builder"
ensure_builder

source "$repo_root/scripts/local-ci-fingerprint-lib.sh"

head_sha="$(git rev-parse HEAD)"
branch="$(git branch --show-current || true)"
worktree_fingerprint="$(fingerprint_paths repository .)"
git_status="$(git status --short --untracked-files=all)"
if [[ -n "$git_status" ]]; then
  source_subject="${head_sha}+worktree:${worktree_fingerprint}"
else
  source_subject="$head_sha"
fi
compute_local_ci_component_fingerprints
verification_fingerprint="$(
  printf 'subject=%s\nsource-bytes=%s\nbackend=%s\nfrontend=%s\nbaseline=%s\nplaywright=%s\n' \
    "$source_subject" "$worktree_fingerprint" "$backend_fingerprint" "$frontend_fingerprint" \
    "$baseline_fingerprint" "$playwright_image" \
    | sha256sum | awk '{print $1}'
)"

backend_image="jilinjobs-cms-local/backend:${backend_fingerprint}"
review_backend_image="jilinjobs-cms-local/review-backend:${backend_fingerprint}"
migration_image="jilinjobs-cms-local/content-migration:${backend_fingerprint}"
frontend_image="jilinjobs-cms-local/frontend:${frontend_fingerprint}"
baseline_image="jilinjobs-cms-local/review-baseline:${baseline_fingerprint}"
verification_image="jilinjobs-cms-local/review-verification:${verification_fingerprint}"

{
  printf 'head=%s\n' "$head_sha"
  printf 'branch=%s\n' "$branch"
  printf 'source_subject=%s\n' "$source_subject"
  printf 'worktree_fingerprint=%s\n' "$worktree_fingerprint"
  printf 'backend_fingerprint=%s\n' "$backend_fingerprint"
  printf 'frontend_fingerprint=%s\n' "$frontend_fingerprint"
  printf 'baseline_fingerprint=%s\n' "$baseline_fingerprint"
  printf 'review_control_fingerprint=%s\n' "$review_control_fingerprint"
  printf 'review_runtime_fingerprint=%s\n' "$review_runtime_fingerprint"
  printf 'verification_fingerprint=%s\n' "$verification_fingerprint"
  printf 'base_ref=%s\n' "$base_ref"
  printf 'npm_registry=%s\n' "$npm_registry"
  printf 'started_at=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '\n[git status]\n'
  printf '%s\n' "$git_status"
} | tee "$evidence_dir/subject.txt"

docker system df -v > "$evidence_dir/docker-before.txt" 2>&1 || true

changed_file_list="$run_root/changed-files.txt"
{
  if git rev-parse --verify "$base_ref^{commit}" >/dev/null 2>&1; then
    merge_base="$(git merge-base HEAD "$base_ref")"
    git diff --name-only "$merge_base"...HEAD
  fi
  git diff --name-only
  git diff --cached --name-only
  git ls-files -o --exclude-standard
} | awk 'NF' | sort -u > "$changed_file_list"
cp "$changed_file_list" "$evidence_dir/changed-files.txt"

changed_matches() { grep -Eq "$1" "$changed_file_list"; }

force_specialized="${LOCAL_CI_FORCE_SPECIALIZED:-false}"
run_canonical=false
run_upgrade=false
if [[ "$force_specialized" == "true" ]] || changed_matches \
  '^(data-migrations/party/v1/|backend/(build\.gradle\.kts|settings\.gradle\.kts|modules/cms-core/|apps/cms-server/|apps/content-migration/)|\.github/workflows/canonical-migration-verify\.yml$)'; then
  run_canonical=true
fi
if [[ "$force_specialized" == "true" ]] || changed_matches \
  '^(data-migrations/party/v1/|backend/(build\.gradle\.kts|settings\.gradle\.kts|modules/cms-core/|apps/cms-server/|apps/content-migration/)|\.github/workflows/eu30-migration-upgrade-verify\.yml$)'; then
  run_upgrade=true
fi

say "Verify Git Commit Message policy"
python3 scripts/verify-git-commit-message.py --base-ref "$base_ref" 2>&1 | tee "$evidence_dir/commit-message.log"

say "Start fresh MySQL 8.4"
remove_container "$mysql_container"
docker run -d --name "$mysql_container" --network host \
  -e MYSQL_ROOT_PASSWORD=root -e MYSQL_ROOT_HOST=% \
  "$mysql_image" --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci >/dev/null
for i in $(seq 1 60); do
  if docker exec "$mysql_container" mysql -uroot -proot -N -B -e 'SELECT 1' >/dev/null 2>&1; then break; fi
  if [[ "$i" -eq 60 ]]; then
    docker logs "$mysql_container" | tee "$evidence_dir/mysql-start.log"
    die "MySQL did not become ready with the configured CI credentials"
  fi
  sleep 2
done

mysql_exec() {
  docker exec "$mysql_container" mysql --default-character-set=utf8mb4 -uroot -proot "$@"
}
mysql_query() {
  local database="$1" sql="$2"
  docker exec "$mysql_container" mysql --default-character-set=utf8mb4 \
    -uroot -proot "$database" -N -B -e "$sql"
}
reset_database() {
  local database="$1"
  mysql_exec -e "DROP DATABASE IF EXISTS \`$database\`; CREATE DATABASE \`$database\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
}

for db in site_package_verify migration_boundary generic_content_migration generic_list_item_compatibility; do
  reset_database "$db"
done

gradle_docker_env() {
  local db_url="$1"
  shift
  docker run --rm --network host \
    --user "$uid:$gid" -e HOME=/tmp -e GRADLE_USER_HOME=/gradle-cache \
    -e DB_URL="$db_url" -e DB_USERNAME=root -e DB_PASSWORD=root \
    -v "$repo_root:/workspace" -v "$cache_root/gradle:/gradle-cache" \
    -w /workspace/backend "$gradle_image" gradle "$@"
}
node_docker() {
  local workdir="$1"
  shift
  docker run --rm --network host \
    --user "$uid:$gid" -e HOME=/tmp -e npm_config_cache=/npm-cache \
    -e NPM_CONFIG_REGISTRY="$npm_registry" -e NPM_CONFIG_REPLACE_REGISTRY_HOST=always \
    -v "$repo_root:/workspace" -v "$cache_root/npm:/npm-cache" \
    -w "/workspace/$workdir" "$node_image" "$@"
}

say "Verify Consumer documentation governance"
node_docker . node scripts/verify-docs-governance.mjs 2>&1 | tee "$evidence_dir/docs-governance.log"
node_docker . npx --yes @google/design.md@0.4.0 lint docs/design/public-site/DESIGN.md 2>&1 | tee "$evidence_dir/design-lint.log"

say "Backend clean build, tests and persistent verification contracts"
docker run --rm --network host \
  --user "$uid:$gid" -e HOME=/tmp -e GRADLE_USER_HOME=/gradle-cache \
  -e 'SITE_PACKAGE_VERIFY_DB_URL=jdbc:mysql://127.0.0.1:3306/site_package_verify?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true' \
  -e SITE_PACKAGE_VERIFY_DB_USERNAME=root -e SITE_PACKAGE_VERIFY_DB_PASSWORD=root \
  -e 'MIGRATION_VERIFY_DB_URL=jdbc:mysql://127.0.0.1:3306/migration_boundary?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true' \
  -e MIGRATION_VERIFY_DB_USERNAME=root -e MIGRATION_VERIFY_DB_PASSWORD=root \
  -e 'GENERIC_MIGRATION_VERIFY_DB_URL=jdbc:mysql://127.0.0.1:3306/generic_content_migration?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true' \
  -e GENERIC_MIGRATION_VERIFY_DB_USERNAME=root -e GENERIC_MIGRATION_VERIFY_DB_PASSWORD=root \
  -e 'GENERIC_COMPATIBILITY_VERIFY_DB_URL=jdbc:mysql://127.0.0.1:3306/generic_list_item_compatibility?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true' \
  -e GENERIC_COMPATIBILITY_VERIFY_DB_USERNAME=root -e GENERIC_COMPATIBILITY_VERIFY_DB_PASSWORD=root \
  -e CMS_STORAGE_ROOT=/workspace/.local-ci/backend-contract/uploads \
  -e CMS_STATIC_ROOT=/workspace/.local-ci/backend-contract/static \
  -v "$repo_root:/workspace" -v "$cache_root/gradle:/gradle-cache" \
  -w /workspace/backend "$gradle_image" \
  gradle clean test bootJar :apps:content-migration:bootJar \
    verifySitePackageFoundation verifyStableSiteStructure \
    verifyRuntimeSitePackageComposition verifySiteBootstrapBaselineSeparation \
    verifySitePackageAssets verifyPageContentOwnership verifyPageContentAdoption \
    verifyLinkOpenModeMigration verifyContentMigrationBoundary \
    verifyGenericContentMigration verifyGenericPageContentMigration \
    verifyGenericListItemCompatibility --no-daemon \
  2>&1 | tee "$evidence_dir/backend.log"

say "Verify site-neutral Content Migration source boundary"
python3 - <<'PY' | tee "$evidence_dir/migration-source-boundary.log"
from pathlib import Path
root = Path("backend/apps/content-migration/src/main/kotlin/com/jilinjobs/cms/migration")
allowed_files = {Path("LegacyMappings.kt")}
unexpected = []
for path in root.rglob("*.kt"):
    relative = path.relative_to(root)
    if relative in allowed_files or relative.parts[0] == "generic":
        continue
    unexpected.append(str(relative))
if unexpected:
    raise SystemExit("Content Migration contains site-specific implementation: " + ", ".join(sorted(unexpected)))
print("site-neutral migration source boundary: PASS")
PY

image_matches() {
  local image="$1" component="$2" fingerprint="$3"
  docker image inspect "$image" >/dev/null 2>&1 \
    && [[ "$(docker image inspect --format '{{ index .Config.Labels "io.jilinjobs.local-ci.component" }}' "$image")" == "$component" ]] \
    && [[ "$(docker image inspect --format '{{ index .Config.Labels "io.jilinjobs.local-ci.input-fingerprint" }}' "$image")" == "$fingerprint" ]]
}
baseline_matches() {
  local image="$1" backend_fp="$2" baseline_fp="$3"
  docker image inspect "$image" >/dev/null 2>&1 \
    && [[ "$(docker image inspect --format '{{ index .Config.Labels "io.jilinjobs.backend-fingerprint" }}' "$image")" == "$backend_fp" ]] \
    && [[ "$(docker image inspect --format '{{ index .Config.Labels "io.jilinjobs.review-baseline-fingerprint" }}' "$image")" == "$baseline_fp" ]]
}
buildx_local_image() {
  local image="$1" component="$2" fingerprint="$3" dockerfile="$4" context="$5"
  if image_matches "$image" "$component" "$fingerprint"; then
    printf 'reuse %s\n' "$image" | tee -a "$evidence_dir/image-reuse.log"
    return
  fi
  docker buildx build --builder "$builder" --load \
    --label io.jilinjobs.local-ci.repository=dygapp/jilinjobs-cms \
    --label "io.jilinjobs.local-ci.component=$component" \
    --label "io.jilinjobs.local-ci.input-fingerprint=$fingerprint" \
    --label "org.opencontainers.image.revision=$head_sha" \
    --label "io.jilinjobs.local-ci.worktree-fingerprint=$worktree_fingerprint" \
    -t "$image" -f "$dockerfile" "$context"
}

say "Build or reuse local Backend runtime images"
buildx_local_image "$backend_image" backend "$backend_fingerprint" backend/Dockerfile.runtime backend 2>&1 | tee "$evidence_dir/backend-image.log"
buildx_local_image "$review_backend_image" review-backend "$backend_fingerprint" backend/Dockerfile.review-runtime backend 2>&1 | tee "$evidence_dir/review-backend-image.log"
buildx_local_image "$migration_image" content-migration "$backend_fingerprint" backend/Dockerfile.migration-runtime backend 2>&1 | tee "$evidence_dir/migration-image.log"

say "Public formal build"
node_docker frontend/public-site npm ci --no-audit --no-fund 2>&1 | tee "$evidence_dir/public-npm-ci.log"
node_docker frontend/public-site npm run build 2>&1 | tee "$evidence_dir/public-build.log"

say "Admin formal build"
node_docker frontend/admin npm ci --no-audit --no-fund 2>&1 | tee "$evidence_dir/admin-npm-ci.log"
node_docker frontend/admin npm run build 2>&1 | tee "$evidence_dir/admin-build.log"

say "Build or reuse combined Frontend runtime image"
frontend_context="$run_root/frontend-runtime"
mkdir -p "$frontend_context/public" "$frontend_context/admin"
cp -a frontend/public-site/dist/. "$frontend_context/public/"
cp -a frontend/admin/dist/. "$frontend_context/admin/"
cp frontend/nginx.e2e.conf "$frontend_context/nginx.conf"
cp frontend/Dockerfile.runtime "$frontend_context/Dockerfile"
buildx_local_image "$frontend_image" frontend "$frontend_fingerprint" "$frontend_context/Dockerfile" "$frontend_context" 2>&1 | tee "$evidence_dir/frontend-image.log"

provision_site() {
  local database="$1"
  gradle_docker_env \
    "jdbc:mysql://127.0.0.1:3306/${database}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true" \
    provisionSitePackage --args="../sites/jilinjobs" --no-daemon
}
run_migration() {
  local database="$1" snapshot="$2" runtime_root="$3"
  mkdir -p "$runtime_root/uploads" "$runtime_root/static"
  docker run --rm --network host --user "$uid:$gid" \
    -e "DB_URL=jdbc:mysql://127.0.0.1:3306/${database}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true" \
    -e DB_USERNAME=root -e DB_PASSWORD=root \
    -e CMS_STORAGE_ROOT=/uploads -e CMS_STATIC_ROOT=/runtime-static \
    -v "$runtime_root/uploads:/uploads" -v "$runtime_root/static:/runtime-static" \
    -v "$snapshot:/snapshot:ro" "$migration_image" /snapshot
}

if [[ "$run_canonical" == "true" ]]; then
  say "Party canonical dataset structure, runtime projection and idempotency"
  python3 scripts/local-ci-party.py validate-current data-migrations/party/v1 | tee "$evidence_dir/canonical-structure.json"
  reset_database canonical_migration
  provision_site canonical_migration 2>&1 | tee "$evidence_dir/canonical-provision.log"
  canonical_runtime="$run_root/canonical-runtime"
  run_migration canonical_migration "$repo_root/data-migrations/party/v1" "$canonical_runtime" 2>&1 | tee "$evidence_dir/canonical-first-import.log"
  mysql_query canonical_migration \
    "SELECT i.sort_order,i.title,i.source_type,COALESCE(i.article_id,''),COALESCE(am.legacy_key,''),COALESCE(i.image_path,''),COALESCE(i.image_resource_id,''),COALESCE(r.storage_key,''),COALESCE(m.image_sha256,'') FROM cms_list_item i JOIN cms_list l ON l.id=i.list_id JOIN cms_list_item_legacy_mapping m ON m.list_item_id=i.id LEFT JOIN cms_article_legacy_mapping am ON am.article_id=i.article_id LEFT JOIN cms_resource r ON r.id=i.image_resource_id WHERE l.code='PARTY_CAROUSEL' ORDER BY i.sort_order" \
    > "$evidence_dir/canonical-carousel-db.tsv"
  python3 scripts/local-ci-party.py verify-canonical-first \
    data-migrations/party/v1/manifest.json "$evidence_dir/canonical-first-import.log" \
    "$evidence_dir/canonical-carousel-db.tsv" "$canonical_runtime"
  run_migration canonical_migration "$repo_root/data-migrations/party/v1" "$canonical_runtime" 2>&1 | tee "$evidence_dir/canonical-second-import.log"
  article_count="$(mysql_query canonical_migration "SELECT COUNT(*) FROM cms_article_legacy_mapping WHERE source_system='legacy-jilinjobs'")"
  list_count="$(mysql_query canonical_migration "SELECT COUNT(*) FROM cms_list_item_legacy_mapping WHERE source_system='legacy-jilinjobs'")"
  python3 scripts/local-ci-party.py verify-canonical-second data-migrations/party/v1/manifest.json \
    "$evidence_dir/canonical-second-import.log" "$article_count" "$list_count"
else
  printf 'SKIP: Party canonical specialized path not affected.\n' | tee "$evidence_dir/canonical-specialized.log"
fi

if [[ "$run_upgrade" == "true" ]]; then
  say "Accepted EU-29 runtime to current Generic canonical migration compatibility"
  eu29_commit=59c855f55899cd613fdee059b27db762ffa3b092
  if ! git cat-file -e "${eu29_commit}^{commit}" 2>/dev/null; then git fetch origin "$eu29_commit" --depth=1; fi
  [[ "$(git rev-parse "${eu29_commit}^{commit}")" == "$eu29_commit" ]] || die "EU-29 accepted commit identity mismatch"
  eu29_root="$run_root/eu29-accepted"
  mkdir -p "$eu29_root"
  git archive "$eu29_commit" data-migrations/party/v1 | tar -x -C "$eu29_root"
  python3 scripts/local-ci-party.py prepare-eu29 "$eu29_root/data-migrations/party/v1"

  reset_database migration_upgrade
  provision_site migration_upgrade 2>&1 | tee "$evidence_dir/upgrade-provision.log"
  upgrade_runtime="$run_root/upgrade-runtime"
  run_migration migration_upgrade "$eu29_root/data-migrations/party/v1" "$upgrade_runtime" 2>&1 | tee "$evidence_dir/eu29-upgrade-import.log"
  mysql_query migration_upgrade \
    "SELECT i.id,i.source_type,COALESCE(i.article_id,''),COALESCE(i.image_path,''),COALESCE(i.image_resource_id,''),m.source_fingerprint,m.image_sha256 FROM cms_list_item i JOIN cms_list l ON l.id=i.list_id JOIN cms_list_item_legacy_mapping m ON m.list_item_id=i.id WHERE l.code='PARTY_CAROUSEL' AND m.legacy_key='party-carousel:position:2'" \
    > "$evidence_dir/eu29-position2-before.tsv"
  python3 scripts/local-ci-party.py verify-upgrade-old "$evidence_dir/eu29-upgrade-import.log" "$evidence_dir/eu29-position2-before.tsv" "$run_root/eu29-position2-id.txt"

  run_migration migration_upgrade "$repo_root/data-migrations/party/v1" "$upgrade_runtime" 2>&1 | tee "$evidence_dir/current-upgrade-import.log"
  mysql_query migration_upgrade \
    "SELECT i.id,i.source_type,COALESCE(i.article_id,''),COALESCE(am.legacy_key,''),COALESCE(i.image_path,''),COALESCE(i.image_resource_id,''),COALESCE(r.storage_key,''),m.source_fingerprint,m.image_sha256 FROM cms_list_item i JOIN cms_list l ON l.id=i.list_id JOIN cms_list_item_legacy_mapping m ON m.list_item_id=i.id LEFT JOIN cms_article_legacy_mapping am ON am.article_id=i.article_id LEFT JOIN cms_resource r ON r.id=i.image_resource_id WHERE l.code='PARTY_CAROUSEL' AND m.legacy_key='party-carousel:position:2'" \
    > "$evidence_dir/current-position2-after.tsv"
  python3 scripts/local-ci-party.py verify-upgrade-current "$evidence_dir/current-upgrade-import.log" "$evidence_dir/current-position2-after.tsv" "$run_root/eu29-position2-id.txt" "$upgrade_runtime/uploads"

  run_migration migration_upgrade "$repo_root/data-migrations/party/v1" "$upgrade_runtime" 2>&1 | tee "$evidence_dir/current-upgrade-second-import.log"
  python3 scripts/local-ci-party.py verify-upgrade-second "$evidence_dir/current-upgrade-second-import.log"

  mysql_exec migration_upgrade -e "UPDATE cms_list_item_legacy_mapping SET source_fingerprint=REPEAT('f',64) WHERE legacy_key='party-carousel:position:2';"
  set +e
  run_migration migration_upgrade "$repo_root/data-migrations/party/v1" "$upgrade_runtime" > "$evidence_dir/current-position2-conflict.log" 2>&1
  conflict_status=$?
  set -e
  [[ "$conflict_status" -ne 0 ]] || die "mapping fingerprint drift was not rejected"
  python3 scripts/local-ci-party.py verify-upgrade-conflict "$evidence_dir/current-position2-conflict.log"
else
  printf 'SKIP: EU-29 -> current upgrade specialized path not affected.\n' | tee "$evidence_dir/upgrade-specialized.log"
fi

say "Fresh integrated Runtime and complete Public/Admin browser verification"
reset_database jilinjobs_cms
runtime_root="$run_root/integrated-runtime"
mkdir -p "$runtime_root/static" "$runtime_root/uploads"
remove_container "$backend_container"
docker run -d --name "$backend_container" --network host --user "$uid:$gid" \
  -e 'DB_URL=jdbc:mysql://127.0.0.1:3306/jilinjobs_cms?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true' \
  -e DB_USERNAME=root -e DB_PASSWORD=root \
  -e CMS_STATIC_ROOT=/runtime-static -e CMS_STORAGE_ROOT=/uploads \
  -e CMS_SITE_PACKAGE_ROOT=/site-package -e CMS_SITE_PACKAGE_BOOTSTRAP_ON_START=true \
  -e CMS_REVIEW_IDENTITY_TOKEN=cms-local-review-admin \
  -v "$runtime_root/static:/runtime-static" -v "$runtime_root/uploads:/uploads" \
  -v "$repo_root/sites/jilinjobs:/site-package:ro" "$review_backend_image" >/dev/null
for i in $(seq 1 60); do
  if curl --fail --silent http://127.0.0.1:8080/api/public/site-config >/dev/null; then break; fi
  if [[ "$i" -eq 60 ]]; then
    docker logs "$backend_container" | tee "$evidence_dir/integrated-backend.log"
    die "Backend runtime did not become ready"
  fi
  sleep 2
done
curl --fail --silent http://127.0.0.1:8080/static/health/baseline.png >/dev/null
anonymous_admin_status="$(curl --silent --output /dev/null --write-out '%{http_code}' http://127.0.0.1:8080/api/admin/columns)"
[[ "$anonymous_admin_status" == "401" ]] || die "Anonymous Admin request should return 401, got $anonymous_admin_status"
invalid_review_status="$(curl --silent --output /dev/null --write-out '%{http_code}' -H 'X-Cms-Review-Credential: invalid-review-credential' http://127.0.0.1:8080/api/admin/columns)"
[[ "$invalid_review_status" == "401" ]] || die "Invalid Review credential should return 401, got $invalid_review_status"
curl --fail --silent -H 'X-Cms-Review-Credential: cms-local-review-admin' http://127.0.0.1:8080/api/admin/columns >/dev/null

remove_container "$frontend_container"
docker run -d --name "$frontend_container" --network host "$frontend_image" >/dev/null
for i in $(seq 1 30); do
  if curl --fail --silent http://127.0.0.1:5173/ >/dev/null && curl --fail --silent http://127.0.0.1:5173/admin/ >/dev/null; then break; fi
  if [[ "$i" -eq 30 ]]; then
    docker logs "$frontend_container" | tee "$evidence_dir/integrated-frontend.log"
    die "Frontend runtime did not become ready"
  fi
  sleep 1
done

docker run --rm --init --ipc=host --network host --user "$uid:$gid" \
  -e HOME=/tmp -e CI=true -e CI_EXTERNAL_WEB_SERVER=true -e PARTY_REFERENCE_EVIDENCE=false \
  -v "$repo_root/frontend/public-site:/work" -w /work "$playwright_image" \
  npm run test:e2e 2>&1 | tee "$evidence_dir/public-e2e.log"

docker run --rm --init --ipc=host --network host --user "$uid:$gid" \
  -e HOME=/tmp -e CI=true -v "$repo_root/frontend/admin:/work" -w /work "$playwright_image" \
  npm run test:e2e 2>&1 | tee "$evidence_dir/admin-e2e.log"

remove_container "$backend_container"
remove_container "$frontend_container"

say "Review Runtime baseline/probe cache"
baseline_exists=false
if baseline_matches "$baseline_image" "$backend_fingerprint" "$baseline_fingerprint"; then
  baseline_exists=true
  printf 'reuse %s\n' "$baseline_image" | tee -a "$evidence_dir/image-reuse.log"
fi
verification_exists=false
if image_matches "$verification_image" review-verification "$verification_fingerprint"; then
  verification_exists=true
  printf 'reuse %s\n' "$verification_image" | tee -a "$evidence_dir/image-reuse.log"
fi

if [[ "$verification_exists" != "true" ]]; then
  if [[ "$baseline_exists" != "true" ]]; then
    BACKEND_IMAGE="$backend_image" MIGRATION_IMAGE="$migration_image" BASELINE_IMAGE="$baseline_image" \
    BACKEND_FINGERPRINT="$backend_fingerprint" BASELINE_FINGERPRINT="$baseline_fingerprint" SOURCE_SHA="$head_sha" \
      bash scripts/prepare-review-baseline.sh 2>&1 | tee "$evidence_dir/review-baseline-build.log"
  fi

  BASELINE_IMAGE="$baseline_image" EXPECTED_BASELINE_FINGERPRINT="$baseline_fingerprint" EXPECTED_BACKEND_FINGERPRINT="$backend_fingerprint" \
    bash scripts/restore-review-baseline.sh 2>&1 | tee "$evidence_dir/review-baseline-restore.log"

  BACKEND_IMAGE="$review_backend_image" FRONTEND_IMAGE="$frontend_image" \
    bash scripts/start-review-runtime.sh 2>&1 | tee "$evidence_dir/review-runtime-start.log"

  python3 scripts/verify-review-runtime.py http://127.0.0.1:5173 | tee "$evidence_dir/review-baseline-runtime.json"

  docker run --rm --init --ipc=host --network host --user "$uid:$gid" \
    -e HOME=/tmp -e CI=true -e CI_EXTERNAL_WEB_SERVER=true -e PARTY_MIGRATION_RUNTIME=true \
    -v "$repo_root/frontend/public-site:/work" -w /work "$playwright_image" \
    npx playwright test tests/e2e/party-migration-runtime.spec.ts --project=chromium --reporter=line \
    2>&1 | tee "$evidence_dir/review-party-runtime-e2e.log"

  marker_context="$run_root/review-verification-marker"
  mkdir -p "$marker_context"
  SOURCE_SUBJECT="$source_subject" BACKEND_FP="$backend_fingerprint" FRONTEND_FP="$frontend_fingerprint" \
  BASELINE_FP="$baseline_fingerprint" REVIEW_RUNTIME_FP="$review_runtime_fingerprint" VERIFICATION_FP="$verification_fingerprint" \
    python3 - "$marker_context/verification.json" <<'PY'
import json, os, pathlib, sys
path = pathlib.Path(sys.argv[1])
path.write_text(json.dumps({
    "schemaVersion": 2,
    "sourceSubject": os.environ["SOURCE_SUBJECT"],
    "backendFingerprint": os.environ["BACKEND_FP"],
    "frontendFingerprint": os.environ["FRONTEND_FP"],
    "baselineFingerprint": os.environ["BASELINE_FP"],
    "reviewRuntimeFingerprint": os.environ["REVIEW_RUNTIME_FP"],
    "verificationFingerprint": os.environ["VERIFICATION_FP"],
}, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8")
PY
  cat > "$marker_context/Dockerfile" <<'EOF'
FROM alpine:3.23
COPY verification.json /verification.json
EOF
  buildx_local_image "$verification_image" review-verification "$verification_fingerprint" \
    "$marker_context/Dockerfile" "$marker_context" 2>&1 | tee "$evidence_dir/review-verification-image.log"
else
  printf 'Review verification marker cache hit after current full build/test/E2E claims.\n' | tee "$evidence_dir/review-runtime-cache.log"
fi

for path in review-baseline-build/manifest.json review-baseline-restore/manifest.json review-verification.json; do
  if [[ -f "$path" ]]; then cp "$path" "$evidence_dir/$(basename "$(dirname "$path")")-$(basename "$path")"; fi
done

remove_container cms-backend
remove_container cms-frontend
remove_container review-baseline-backend
remove_container review-baseline-copy

docker run --rm -v "$repo_root:/repo" "$alpine_image" sh -c \
  'rm -rf /repo/runtime-static /repo/runtime-uploads /repo/review-baseline-build /repo/review-main-subset /repo/review-baseline-restore /repo/runtime-review-meta /repo/review-verification-marker' >/dev/null

say "Bound project-local images and record final resource state"
current_images="$backend_image
$review_backend_image
$migration_image
$frontend_image
$baseline_image
$verification_image"
while IFS= read -r ref; do
  [[ -z "$ref" ]] && continue
  if ! grep -Fxq "$ref" <<<"$current_images"; then docker image rm "$ref" >/dev/null 2>&1 || true; fi
done < <(project_image_refs)

docker system df -v > "$evidence_dir/docker-after.txt" 2>&1 || true
docker buildx du --builder "$builder" > "$evidence_dir/buildx-after.txt" 2>&1 || true
printf '%s\n' "$run_id" > "$evidence_root/latest.txt"
{
  printf 'result=PASS\n'
  printf 'completed_at=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'subject=%s\n' "$source_subject"
  printf 'backend_image=%s\n' "$backend_image"
  printf 'review_backend_image=%s\n' "$review_backend_image"
  printf 'migration_image=%s\n' "$migration_image"
  printf 'frontend_image=%s\n' "$frontend_image"
  printf 'baseline_image=%s\n' "$baseline_image"
  printf 'verification_image=%s\n' "$verification_image"
  printf 'review_runtime_fingerprint=%s\n' "$review_runtime_fingerprint"
  printf 'canonical_specialized=%s\n' "$run_canonical"
  printf 'upgrade_specialized=%s\n' "$run_upgrade"
} | tee "$evidence_dir/result.txt"

mapfile -t old_evidence < <(find "$evidence_root" -mindepth 1 -maxdepth 1 -type d -printf '%T@ %p\n' \
  | sort -nr | awk 'NR>3 {sub(/^[^ ]+ /, ""); print}')
if [[ "${#old_evidence[@]}" -gt 0 ]]; then rm -rf "${old_evidence[@]}"; fi

say "Local Docker CI PASS"
printf 'Evidence: %s\n' "$evidence_dir"
