-- JilinJobs fresh-site initial operational defaults.
-- This script is applied once after stable Site Package structure provisioning.
-- After bootstrap, these rows are ordinary operator-managed data and are never reconciled by Site Package runtime composition.

-- Main homepage carousel.
INSERT INTO cms_list_item(list_id, source_type, title, url, image_path, open_mode, sort_order, enabled)
VALUES ((SELECT id FROM cms_list WHERE code='HOME_CAROUSEL'), 'LINK', '这里美得不愿离开', 'https://mp.weixin.qq.com/s/fUv21IynaUh_N8OjjLkDXQ', '/static/home/carousel-01.jpg', '_blank', 10, 1);

-- Main related links.
INSERT INTO cms_list_item(list_id, source_type, title, url, open_mode, sort_order, enabled) VALUES
((SELECT id FROM cms_list WHERE code='SITE_RELATED'), 'LINK', '中国高等教育学生信息网', 'https://www.chsi.com.cn/', '_blank', 10, 1),
((SELECT id FROM cms_list WHERE code='SITE_RELATED'), 'LINK', '国家大学生就业服务平台', 'https://www.ncss.cn/', '_blank', 20, 1),
((SELECT id FROM cms_list WHERE code='SITE_RELATED'), 'LINK', '学历认证', 'https://www.chsi.com.cn/xlrz/paper/report/gdjyxl.action', '_blank', 30, 1),
((SELECT id FROM cms_list WHERE code='SITE_RELATED'), 'LINK', '全国征兵网', 'https://www.gfbzb.gov.cn/', '_blank', 40, 1),
((SELECT id FROM cms_list WHERE code='SITE_RELATED'), 'LINK', '吉林省教育厅', 'https://jyt.jl.gov.cn/', '_blank', 50, 1);

-- Provincial / regional graduate employment links.
INSERT INTO cms_list_item(list_id, source_type, title, url, open_mode, sort_order, enabled) VALUES
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '北京毕业生就业创业服务平台', 'https://fuwu.rsj.beijing.gov.cn/bjdkhy/bysjycy/', '_blank', 10, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '天津公共就业服务网智慧招聘频道', 'https://www.cnthr.com/', '_blank', 20, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '河北高校毕业生招聘专区', 'https://rst.hebei.gov.cn/ggzp/ww/a/b/wwab_gxbyszp.html', '_blank', 30, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '山西省公共招聘网', 'https://sxjy.rst.shanxi.gov.cn/sxscwebui/', '_blank', 40, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '内蒙古高等院校毕业生就业信息网', 'https://zph.nmrc.com.cn/', '_blank', 50, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '山东省高等院校毕业生就业信息网', 'https://www.sdgxbys.cn/col/sdjyfwpt/index.html', '_blank', 60, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '江苏省人才服务云平台', 'https://www.jssrcfwypt.org.cn/rcfwypt/?areaCode=320000', '_blank', 70, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '安徽公共招聘网高校毕业生专区', 'https://www.ahggzp.gov.cn/ww/b/a/wwba_graduates.html', '_blank', 80, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '浙江人才服务网', 'https://www.zjrc.com/zjrcw/#/activityList', '_blank', 90, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '福建省毕业生就业创业公共服务网', 'https://220.160.52.58/', '_blank', 100, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '乐业上海第一站', 'https://jobs.rsj.sh.gov.cn/ggzp-shrs/index.html#/', '_blank', 110, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '辽宁省大学生就业创业服务平台', 'http://bys.lnrc.com.cn/index.do', '_blank', 120, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '吉林人才网', 'https://www.jlrc.com.cn/ww/index.html', '_blank', 130, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '黑龙江省大学生就业创业服务平台', 'https://www.hljbys.org.cn/', '_blank', 140, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '广东公共求职招聘服务平台高校毕业生专区', 'https://ggfw.hrss.gd.gov.cn/recruitment/internet/main/#/graduateZone', '_blank', 150, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '广西毕业生就业服务平台', 'https://bys.gxrc.com/', '_blank', 160, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '海南省公共招聘网', 'https://zhaopin.hainan.gov.cn/#/recruit/home', '_blank', 170, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '湖北省高等院校毕业生就业信息网', 'https://www.hbbys.com.cn/', '_blank', 180, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '湖南大学生就业服务平台', 'https://employment.hunan.smartedu.cn/', '_blank', 190, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '河南省大学生就业服务平台', 'https://hnbysjy.jyt.henan.gov.cn/zp/', '_blank', 200, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '江西人才服务网', 'https://www.jxrcfw.com/', '_blank', 210, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '四川大学生就业服务平台', 'https://bigdata.scbdc.edu.cn:8888/', '_blank', 220, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '云南省高等院校毕业生就业信息网', 'https://www.ynhr.com/index.php?m=home&c=gxfw&a=index', '_blank', 230, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '贵州省高等院校毕业生就业信息网', 'https://gzggzpw.gzsrs.cn/app/graduates/graduates.shtml', '_blank', 240, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '西藏自治区高等院校毕业生就业信息网', 'https://www.xzggjyfw.cn/', '_blank', 250, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '重庆市高等院校毕业生就业信息网', 'https://ggfw.rlsbj.cq.gov.cn/cqjy/', '_blank', 260, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '宁夏高等院校毕业生就业信息网', 'http://www.nxjob.cn/wcms/nxjob/byszp/', '_blank', 270, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '新疆高等院校毕业生就业信息网', 'https://www.xjggjy.com/', '_blank', 280, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '青海省高等院校毕业生就业信息网', 'https://qhrsggfw.org.cn/qhrst/index/qhrs/talant/index.jspx', '_blank', 290, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '陕西省高等院校毕业生就业信息网', 'https://job.snhrm.com/app/article/content/newArticleAction.shtml', '_blank', 300, 1),
((SELECT id FROM cms_list WHERE code='SITE_REGIONAL_GRADUATES'), 'LINK', '甘肃省高等院校毕业生就业信息网', 'https://www.gszhaopin.com/', '_blank', 310, 1);

-- Jilin universities.
INSERT INTO cms_list_item(list_id, source_type, title, url, open_mode, sort_order, enabled) VALUES
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林大学', 'https://www.jlu.edu.cn/', '_blank', 10, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '东北师范大学', 'https://www.nenu.edu.cn/', '_blank', 20, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春理工大学', 'http://www.cust.edu.cn/', '_blank', 30, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '延边大学', 'https://www.ybu.edu.cn/', '_blank', 40, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林农业大学', 'https://www.jlau.edu.cn/', '_blank', 50, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '北华大学', 'http://www.beihua.edu.cn/', '_blank', 60, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春工业大学', 'https://www.ccut.edu.cn/', '_blank', 70, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '东北电力大学', 'https://www.neepu.edu.cn/', '_blank', 80, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春中医药大学', 'http://www.ccucm.edu.cn//', '_blank', 90, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林师范大学', 'http://www.jlnu.edu.cn/', '_blank', 100, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林财经大学', 'http://www.jlufe.edu.cn/', '_blank', 110, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林外国语大学', 'https://www.jisu.edu.cn/', '_blank', 120, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春大学', 'https://www.ccu.edu.cn/', '_blank', 130, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林建筑大学', 'https://www.jlju.edu.cn/', '_blank', 140, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林化工大学', 'https://www.jluct.edu.cn/', '_blank', 150, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春工程学院', 'https://www.ccit.edu.cn/', '_blank', 160, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林农业科技学院', 'https://www.jlnku.edu.cn/', '_blank', 170, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林医药学院', 'https://www.jlmu.cn/', '_blank', 180, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春师范大学', 'https://www.ccsfu.edu.cn/', '_blank', 190, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '通化师范学院', 'http://www.thnu.edu.cn/', '_blank', 200, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林工程技术师范学院', 'https://www.jlenu.edu.cn/', '_blank', 210, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '白城师范学院', 'https://www.bcnu.edu.cn/', '_blank', 220, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林工商学院', 'https://www.jlbtc.edu.cn/', '_blank', 230, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林体育学院', 'http://www.jlsu.edu.cn/index.html', '_blank', 240, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林艺术学院', 'https://www.jlart.edu.cn/', '_blank', 250, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林警察学院', 'https://www.jljcxy.com/', '_blank', 260, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林动画学院', 'https://www.jlai.edu.cn/', '_blank', 270, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林省教育学院', 'https://www.jlsjyxy.com.cn/', '_blank', 280, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林开放大学', 'http://www.jlrtvu.jl.cn/', '_blank', 290, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林省经济管理干部学院', 'https://www.jlemcc.edu.cn/', '_blank', 300, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春汽车职业技术大学', 'https://www.caii.edu.cn/', '_blank', 310, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春金融高等专科学校', 'http://www.cjgz.edu.cn/', '_blank', 320, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春医学高等专科学校', 'http://www.ccmc.edu.cn/', '_blank', 330, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '白城医学高等专科学校', 'http://www.bcyz.cn/', '_blank', 340, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林交通职业技术学院', 'https://www.jljy.edu.cn/', '_blank', 350, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林电子信息职业技术学院', 'http://www.jltc.edu.cn/', '_blank', 360, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林工业职业技术学院', 'http://www.jvcit.edu.cn/', '_blank', 370, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林铁道职业技术大学', 'https://www.jty.edu.cn/', '_blank', 380, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林工程职业学院', 'https://www.jlevc.cn/', '_blank', 390, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林司法警官职业学院', 'https://www.jlsfjy.cn/', '_blank', 400, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '四平职业大学', 'http://www.spvu.edu.cn/', '_blank', 410, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '辽源职业技术学院', 'http://www.lyvtc.cn/', '_blank', 420, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春职业技术大学', 'https://www.cvit.edu.cn/', '_blank', 430, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '松原职业技术学院', 'http://www.sypt.cn/', '_blank', 440, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '白城职业技术学院', 'https://www.bcvit.cn/', '_blank', 450, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长白山职业技术学院', 'http://www.cbsvtc.com.cn/', '_blank', 460, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '延边职业技术学院', 'http://www.ybvtc.com/', '_blank', 470, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春医药职业学院', 'https://www.dfzyxy.net/', '_blank', 480, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春信息技术职业学院', 'https://www.citpc.edu.cn/', '_blank', 490, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林科技职业技术学院', 'https://www.jilinkj.com/', '_blank', 500, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春人文学院', 'https://www.ccrw.edu.cn/', '_blank', 510, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春光华学院', 'http://www.ghu.edu.cn/', '_blank', 520, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春大学旅游学院', 'https://www.tccu.edu.cn/', '_blank', 530, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春电子科技学院', 'https://www3.changdian2001.com/', '_blank', 540, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春工业大学人文信息学院', 'http://www.ccutchi.com/', '_blank', 550, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春科技学院', 'http://www.jlaudev.com.cn/', '_blank', 560, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林师范大学博达学院', 'https://www.bdxy.com.cn/', '_blank', 570, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春财经学院', 'http://www.ccufe.edu.cn/', '_blank', 580, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '吉林建筑科技学院', 'http://www.jluat.edu.cn/', '_blank', 590, 1),
((SELECT id FROM cms_list WHERE code='SITE_JILIN_UNIVERSITIES'), 'LINK', '长春建筑学院', 'https://www.jladi.edu.cn/', '_blank', 600, 1);

INSERT INTO cms_advertisement(slot_id, title, image_path, url, open_mode, sort_order, enabled)
VALUES ((SELECT id FROM cms_ad_slot WHERE code='HOME_RECRUITMENT_PROMO'), '吉林省高校毕业生招聘活动', '/static/home/recruitment-campaign.png', 'https://24365.jl.smartedu.cn/', '_blank', 10, 1);
